[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "solmate/=packages/foundry-example/lib/solmate/src/",
]
verbosity = 1

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000


