name: Ci branch

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: npm install -g nx
      - run: nx deploy nx-skynet --otp ${{ secrets.OTP }}
